In [1]:
print("usama","khan",sep="<>")           ###sep mean sepreter 

usama<>khan


In [13]:
print("usama \nkhan")                 ### back slach line new line               


usama 
khan


In [10]:
print("usama khan","\tpakistan \nzindabad")    ###\t space for 5 in tab rule

usama khan 	pakistan 
zindabad


# Types of variable 
## There are four types of variable 

In [11]:
#####Numbers m 2 types ati he "whole number","decimal number"
###                             12345678910 , 2.1,2.2,2.3, point wale number ko decimal khete he      
### A to z ko alphabet khete he alphabet python m string ko khete he 
### True or  fa;se python m boolean ko khete he 

In [14]:
u = ("usama khan:")             #### string parameter pass keye 
print(type(u))

<class 'str'>


In [15]:
num = (23)                    #### number ko python m int khete he 
print(type(num))

<class 'int'>


In [16]:
k = (234.7)                 ### point wali jo value hogi python float consider karega
print(type(k))

<class 'float'>


In [18]:
u==u                       ###boolean equal ke use ke leye use karte he true ya false return kare ga 

True

In [19]:
u == k 

False

# concatenation ke leye + ka sign use krte he 2  string ko add krta he 

In [ ]:
u = ("usama khan")
k = (" pakistan zindabad")
print(u + k)

In [26]:
first_name = ("usama khan ")
last_name = ("where are u from:")
print(first_name + last_name)

usama khan where are u from:


# String function 

In [27]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje ")
print(first_variable_name.capitalize())                 ###capitalize  m jo small hoga first letter ouse capital kr den ga 

Usama kha ho m apko deakh rha mil nh rahy ap to muje 


In [29]:
first_variable_name = ("Usama kha Ho m apko deakh rha mil nh rahy ap to muje ")
print(first_variable_name.casefold())                    ### casefold m jo capital hoga wo small ho jay ga 

usama kha ho m apko deakh rha mil nh rahy ap to muje 


In [30]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje ")
print(first_variable_name.count("o"))                   ###count ka function pure sting m "o" kitni bar aya wo bta rha 

3


In [31]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje")
print(first_variable_name.encode())                   ### encode ka function string ko code m dal dega 

b'usama kha ho m apko deakh rha mil nh rahy ap to muje '


In [1]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje")
print(first_variable_name.endswith("muje"))         ##endswith ka function end m is value pr khatam ho rha to True dega

True


In [8]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje ")
print(first_variable_name.find("muje"))           ###find ka function jo ap string doge ouse ka index btaye ga 

48


In [12]:
first_variable_name = ("usama kha ho m {apko} deakh rha mil nh rahy ap to muje ")
print(first_variable_name.index("u"))          ###index bta dega ke ye sting apke kn si index m pari he 

0


In [15]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje12")
print(first_variable_name.isalnum()#isalnum function alphabet hon ge to wo ture dega pr is m spaces lage he is leye false de rha

False


In [11]:
first_variable_name = ("usamakhahomapkodeakhrhamilnhrahyaptomuje")
print(first_variable_name.isalnum())      ## is m spacces nh te to True return kya sare alphabet te 

True


In [1]:
first_variable_name = ("usamakhahomapkodeakhrhaminhrahyaptomuje")
print(first_variable_name.isalpha())     ##isalpha ka function pure string m number kahi be number ajaye to False retuen kare ga 

True


In [31]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje123")
print(first_variable_name.isalpha())

False


In [3]:
first_variable_name = ("123")
print(first_variable_name.isnumeric())       ##isnumeric function string numbers bta ta he just

True


In [7]:
first_variable_name = ("11234567899000966")
print(first_variable_name.isdecimal())      ##isdecimal function number ke leye use hota

True


In [10]:
first_variable_name = ("123456789012")
print(first_variable_name.isdigit())       ### isdigit function mean number he 

True


In [16]:
first_variable_name = ("USAMA Kha Ho  Apko Deakh Rha")
print(first_variable_name.islower())   ### m pouch rha kya ye lower he wo bta rha false ke ye lower nh he 

False


In [21]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje12").title()
print(first_variable_name)
print(first_variable_name.lower())

Usama Kha Ho M Apko Deakh Rha Mil Nh Rahy Ap To Muje12
usama kha ho m apko deakh rha mil nh rahy ap to muje12


In [40]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje12")
print(first_variable_name.join("US"))

Uusama kha ho m apko deakh rha mil nh rahy ap to muje12S


In [22]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje12")
print(first_variable_name.split())      ##split function list m convert kr den ga string ko

['usama', 'kha', 'ho', 'm', 'apko', 'deakh', 'rha', 'mil', 'nh', 'rahy', 'ap', 'to', 'muje12']


In [23]:
first_variable_name = ("            usama kha ho m apko deakh rha mil nh rahy ap to muje12       ")
print(first_variable_name.lstrip())    ##lstrip function left side se spaces remove kr dega 

usama kha ho m apko deakh rha mil nh rahy ap to muje12       


In [24]:
first_variable_name = ("            usama kha ho m apko deakh rha mil nh rahy ap to muje12       ")
print(first_variable_name.rstrip())   ##rstrip function right side se spaces remove kr dega 

            usama kha ho m apko deakh rha mil nh rahy ap to muje12


In [25]:
first_variable_name = ("            usama kha ho m apko deakh rha mil nh rahy ap to muje12       ")
print(first_variable_name.())    ##split function right and left dono jga se spaces remove kr dega 

usama kha ho m apko deakh rha mil nh rahy ap to muje12


In [26]:
first_variable_name = ("usama kha ho m apko deakh rha mil nh rahy ap to muje12")
print(first_variable_name.replace("usama kha ho m apko deakh rha mil nh rahy ap to muje12","kha ho bhai m yaha hu"))
            ###replace function replace kr dega 

kha ho bhai m yaha hu


In [7]:
u = ("usama khan kha ho ap")
j = (" m yahi hu bhai")
print( u + j )

usama khan kha ho ap m yahi hu bhai


In [12]:
u = ("usama khan kha ho ap ")
j = str( 1234)
print( u + j )

usama khan kha ho ap 1234


# String formation

In [2]:
u = ("usama khan kha ho ap ")
j = (1234)
print(f"Assalam o alikum Dear {u} and {j}")

Assalam o alikum Dear usama khan kha ho ap  and 1234


# Type casting and user input

In [3]:
u = input("Enter a value: " )
print(u)

Enter a value: usama
usama


In [4]:
u = int(input("Enter a value: " ))
print(u)                 ###sting ko int m type cast kr lya

Enter a value: 12345
12345


In [1]:
u = int(float(input("Enter a value: " )))
print(u)

Enter a value: 24.67
24


# Operators

In [2]:
u = 234
j = 123
print(u+j)

357


In [5]:
234+123       ( + plus ) operator work

357

In [6]:
123-100       ( - minus ) operator work

23

In [9]:
 123 / 23      ( / divided ) operator work

5.3478260869565215

In [14]:
round(5.3478260869565215,1)    ###round value

5.3

In [15]:
123 //23                     ## // se folat value nh ati

5

In [16]:
12*3            ( * multiply )

36

In [17]:
123 % 12                  ## modulio operator reminder number deta he 

3

In [18]:
12 > 10                  ## 12 bara he 10 se agr jawab tk he to true ho jay ga 

True

In [19]:
10 >12                 ##  10 bara he 12 se to wrong he to false ho jay ga 

False

In [20]:
12 < 10

False

In [21]:
12 <= 10             ### 12 chota  he 10 se ya equal he answer wrong huwa to false a gya 

False

In [22]:
12 >=10             ### 12 bara he 10 se ya equal he answer tk aya to True huwa 

True

In [23]:
10>=10

True

In [24]:
12 != 10         ### 12 ( ! is not ) equal to 10 to answer tk huwa to True return kya 

True

In [25]:
12 != 12

False

In [26]:
12 == 10       ### 12 equal to equal to 10 to wring huwa false aya 
               ### compare ke leye == use karen ge 

False

In [27]:
12 ==12

True

# Bitwise operator (i)  complement sign ~

In [2]:
~50

-51

In [16]:
~67

-68

# Bitwise operator (ii) Ampersand sign &

In [13]:
24 & 28

24

In [14]:
30 & 40

8

In [15]:
50 & 80

16

# Bitwise operator (iii) OR operator sign |

In [1]:
25|27

27

In [2]:
23|29

31

# Bitwise operator (iv) Xor operator sign ^

In [3]:
12 ^25

21

In [4]:
50 ^ 16

34

# Bitwise operator (v) left shift operator sign <<

In [6]:
25 <<3

200

In [7]:
20<<3

160

# list  

In [45]:
u = [1,2,3,4,5,6,7,8,9,0,10,12,34,5,67,8,9,6,4,3,3]
print(type(u))
print(u)

<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 10, 12, 34, 5, 67, 8, 9, 6, 4, 3, 3]


In [40]:
u[2]

3

In [41]:
u[2:9]

[3, 4, 5, 6, 7, 8, 9]

In [46]:
u.append(99)
print(u)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 10, 12, 34, 5, 67, 8, 9, 6, 4, 3, 3, 99]


In [43]:
u.clear()              ## clear ka function puri list clear kr den ga 
u              

[]

In [49]:
u.copy()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 10, 12, 34, 5, 67, 8, 9, 6, 4, 3, 3, 99]

In [50]:
u.count(3)       ## 3 kitni dafa aya he  count kr dega 

3

In [51]:
u.index(99)      ## list m kn si index pr  para he wo bta rha 

21

In [52]:
j = [1,2,3,4,5,6,6,78,7,8,'usama khan']
j

[1, 2, 3, 4, 5, 6, 6, 78, 7, 8, 'usama khan']

In [53]:
j.extend('usama khan')      ## iterable ka matlb he alag alag ho jay ge wo sirf srting pr hota he 
j

[1,
 2,
 3,
 4,
 5,
 6,
 6,
 78,
 7,
 8,
 'usama khan',
 'u',
 's',
 'a',
 'm',
 'a',
 ' ',
 'k',
 'h',
 'a',
 'n']

In [54]:
u.index(99)

21

In [58]:
u.insert(21,100)
u

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 10,
 12,
 34,
 5,
 67,
 8,
 9,
 6,
 4,
 3,
 3,
 100,
 100,
 100,
 99]

In [59]:
u.insert(99,101)
u

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 10,
 12,
 34,
 5,
 67,
 8,
 9,
 6,
 4,
 3,
 3,
 100,
 100,
 100,
 99,
 101]

In [60]:
u.pop()

101

In [75]:
u

[1, 2, 4, 5, 6, 7, 8, 9, 0, 10, 12, 34, 5, 67, 8, 9, 6, 4, 100, 99]

In [63]:
u.pop(22)
u

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 10,
 12,
 34,
 5,
 67,
 8,
 9,
 6,
 4,
 3,
 3,
 100,
 100,
 99]

In [64]:
u.pop(21)

100

In [85]:
u

[0, 1, 2, 4, 4, 5, 5, 6, 6, 7, 8, 8, 9, 9, 10, 12, 34, 67, 99, 100]

In [87]:
u.reverse()
u

[100, 99, 67, 34, 12, 10, 9, 9, 8, 8, 7, 6, 6, 5, 5, 4, 4, 2, 1, 0]

In [89]:
u.sort()
u

[0, 1, 2, 4, 4, 5, 5, 6, 6, 7, 8, 8, 9, 9, 10, 12, 34, 67, 99, 100]

In [92]:
u.sort(reverse=False)
u

[0, 1, 2, 4, 4, 5, 5, 6, 6, 7, 8, 8, 9, 9, 10, 12, 34, 67, 99, 100]

In [93]:
u.sort(reverse=True)
u

[100, 99, 67, 34, 12, 10, 9, 9, 8, 8, 7, 6, 6, 5, 5, 4, 4, 2, 1, 0]

# Bitwise operator (vi) Right shift operator sign >> 

In [8]:
10 >> 2

2

In [9]:
25 >> 3

3

In [10]:
500 >>5

15

# loops

In [1]:
num = [1,2,3,4,5,6,7,8,9,10]
for i in num:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [2]:
for i in range (1,11):
    print(i)
    if i==5:
        break
        
    

1
2
3
4
5


In [5]:
for i in range(1,26):
    if i == 22:
        continue
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
23
24
25


In [12]:
for i in range(10):
    user_input = int(input("Enter your number:"))
    if user_input%2==0:
        print(f"even number{user_input}")
    else:
        print(f"odd nnumber{user_input}")

Enter your number:4
even number4
Enter your number:5
odd nnumber5
Enter your number:7
odd nnumber7
Enter your number:9
odd nnumber9
Enter your number:10
even number10
Enter your number:12
even number12
Enter your number:13
odd nnumber13
Enter your number:14
even number14
Enter your number:15
odd nnumber15
Enter your number:16
even number16


In [20]:
even=[]
odd=[]
for i in range(10):
    user_input = int(input("Enter your number:"))
    if user_input%2==0:
        print(f"even number{user_input}")
        even.append(user_input)
    else:
        print(f"odd nnumber{user_input}")
        odd.append(user_input)
print(even)
print(odd)

Enter your number:2
even number2
Enter your number:3
odd nnumber3
Enter your number:4
even number4
Enter your number:5
odd nnumber5
Enter your number:6
even number6
Enter your number:7
odd nnumber7
Enter your number:8
even number8
Enter your number:8
even number8
Enter your number:9
odd nnumber9
Enter your number:0
even number0
[2, 4, 6, 8, 8, 0]
[3, 5, 7, 9]


In [27]:
user_input = input("Enter your number:").split(',')
even=[]
odd=[]
for i in user_input:
    if int(i)%2==0:
        even.append(i)
    else:
        odd.append(i)
print(f"even: {even}")
print(f"odd: {odd}")

Enter your number:2,4,6,8,10,11,13,15,17
even: ['2', '4', '6', '8', '10']
odd: ['11', '13', '15', '17']


In [6]:
Table = int(input("Enter your number which table print: "))
for i in range(1,11):
    print(f"{Table}*{i}= {Table*i}")

Enter your number which table print: 7
7*1= 7
7*2= 14
7*3= 21
7*4= 28
7*5= 35
7*6= 42
7*7= 49
7*8= 56
7*9= 63
7*10= 70


# while loop

In [4]:
a=10
while a>=0:
    print(a)
    a-=1   
    

10
9
8
7
6
5
4
3
2
1
0


In [ ]:
flag = True
dishes= []
while flag:
    dish = input("Enter your number favourite dishes and q quit: ")
    dishes.append(dish)
    if dish=="q" and dish== "Q":
        flag = False
    else:
        dishes.append(dish)
print(dishes)
    

Enter your number favourite dishes and q quit: w
Enter your number favourite dishes and q quit: e
Enter your number favourite dishes and q quit: r
Enter your number favourite dishes and q quit: t
Enter your number favourite dishes and q quit: Q
Enter your number favourite dishes and q quit: Q


In [75]:
def user_salery(name,eos,current):
    if eos>=1:
        if current<50000:
            increament  = current*.20
            newcurrent = current+increament
            
        elif current>=50000 and current<100000:
            increament = current *.15
            newcurrent = current + increament
            
        elif current>=100000 and current <=1500000:
            increament = current * .10
            newcurrent =  current + increament
            
            
        else:
            increament = current * .5
            newcurrent = current+increament
        print(f"""
             empolyee name : {name}
             eos           : {eos}
             current       : {current}
             increament     :{increament}
             newcurrent    : {newcurrent}
             """) 
            
               
    else:
        print("less then 5")
   
        
        
            

In [76]:
user_salery("usama",2,100000)


             empolyee name : usama
             eos           : 2
             current       : 100000
             increament     :10000.0
             newcurrent    : 110000.0
             


In [77]:
user_salery("maaz",2,60000)


             empolyee name : maaz
             eos           : 2
             current       : 60000
             increament     :9000.0
             newcurrent    : 69000.0
             


# Conditional statement if, elif, else

In [12]:
u = int(input("Enter your age:"))
if u <=17 :
    print("your age is greater then 18")
elif u>=18 and u<=25:
    print("you can drive")
elif u==26:
    print("absulotary yes")
else:
    print("invalid no")

Enter your age:27
invalid no


# Nested if 

In [18]:
fee_status = input ("Do you have paid fee? ")
admit_card = input ("Do you have admit card? ")
roll_no  = input ("Do you have roll no issue? ")
if fee_status == "paid":
    if admit_card == "yes":
        if roll_no == "yes":
            print("you can appear in exam")
    
        else:
            print("you can,t appear in exam without roll no ")
    
    else:
         print("you can,t appear without admit card")
else:
    print("you can,t appear in exam without fee paid")

Do you have paid fee? paid
Do you have admit card? no
Do you have roll no issue? yes
you can,t appear without admit card


In [3]:
import numpy as np

In [13]:
a = np.array([5,6,7,9])
print(a)

[5 6 7 9]


In [14]:
type(a)

numpy.ndarray

In [15]:
u = np.array([[7,8,9],[10,11,12],[13,14,15]])
print(u)

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [10]:
u = [12,13,14,15]
print(u.count(12))

1


In [3]:
import  statistics
u = [125,25,28,33,43]
print (statistics. (u))


33


In [2]:
import numpy as np
import pandas as pd

In [13]:
u = np.array([1,2,3,4,])
u
l = np(u.append(12,56))
l

TypeError: 'numpy.ndarray' object is not callable

In [10]:
j= np.array([2,3,4,5])
j
#j = np.concatenate([u,j])

array([2, 3, 4, 5])

In [12]:
g = np.concatenate([u,j])
g

array([1, 2, 3, 4, 2, 3, 4, 5])

In [11]:
u

array([1, 2, 3, 4])

In [12]:
l

array([12, 56])

In [20]:
list1 = [1,2,3,4,5,6,"usama","false","usama"]
print(list1)

[1, 2, 3, 4, 5, 6, 'usama', 'false', 'usama']


In [21]:
list1.pop()

'usama'

In [22]:
list1

[1, 2, 3, 4, 5, 6, 'usama', 'false']

In [24]:
list1.pop(0)

1

In [25]:
list1

[2, 3, 4, 5, 6, 'usama', 'false']